services:
  postgres:
    image: postgres:16-alpine
    container_name: reminder-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: go-schedule
      POSTGRES_PASSWORD: reminder123
      POSTGRES_DB: go_schedule
      TZ: Asia/Jakarta
      PGTZ: Asia/Jakarta
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: reminder-api
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      TZ: Asia/Jakarta
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  pgdata:
